<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
  'key' => 'group_5a049a7aac468',
  'title' => 'Homepage',
  'fields' => array (
    array (
      'key' => 'field_5a04b91218835',
      'label' => 'Secciones repetibles',
      'name' => 'secciones_repetibles',
      'type' => 'flexible_content',
      'instructions' => 'Click "Add Row" to create a new section.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'layouts' => array (
        '5a04b9246be0b' => array (
          'key' => '5a04b9246be0b',
          'name' => 'section',
          'label' => 'Sección',
          'display' => 'block',
          'sub_fields' => array (
            array (
              'key' => 'field_5a04d2ca5f388',
              'label' => 'Title',
              'name' => 'title',
              'type' => 'text',
              'instructions' => '',
              'required' => 1,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_5a04d32d5f389',
              'label' => 'Display title?',
              'name' => 'display_title',
              'type' => 'true_false',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'message' => '',
              'default_value' => 0,
              'ui' => 0,
              'ui_on_text' => '',
              'ui_off_text' => '',
            ),
            array (
              'key' => 'field_5a04b93a18836',
              'label' => 'Type',
              'name' => 'type',
              'type' => 'select',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'custom-content' => 'Custom Content',
                'page' => 'Page',
                'category' => 'Category',
                'revolution-slider' => 'Revolution Slider',
                'product-categories' => 'Product Categories',
                'product-category' => 'Product Category',
                'product-tag' => 'Product Tag',
                'best-selling' => 'Best Selling Products',
                'on-sale' => 'On Sale Products',
                'popular-products' => 'Popular Products',
                'featured-products' => 'Featured Products',
                'recent-products' => 'Recent Products',
              ),
              'default_value' => array (
                0 => 'custom-content',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 1,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
            ),
            array (
              'key' => 'field_5a04bcc65df33',
              'label' => 'Page Name',
              'name' => 'page_name',
              'type' => 'post_object',
              'instructions' => 'Display page content',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5a04b93a18836',
                    'operator' => '==',
                    'value' => 'page',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'post_type' => array (
                0 => 'page',
              ),
              'taxonomy' => array (
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'return_format' => 'object',
              'ui' => 1,
            ),
            array (
              'key' => 'field_5a04bd5a5df34',
              'label' => 'Category',
              'name' => 'category',
              'type' => 'taxonomy',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5a04b93a18836',
                    'operator' => '==',
                    'value' => 'category',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'taxonomy' => 'category',
              'field_type' => 'select',
              'allow_null' => 0,
              'add_term' => 1,
              'save_terms' => 0,
              'load_terms' => 0,
              'return_format' => 'object',
              'multiple' => 0,
            ),
            array (
              'key' => 'field_5a04c0ce46768',
              'label' => 'Revolution Slider',
              'name' => 'revolution_slider',
              'type' => 'text',
              'instructions' => 'Write the slider alias.',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5a04b93a18836',
                    'operator' => '==',
                    'value' => 'revolution-slider',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_5a04cfa946769',
              'label' => 'Product Category',
              'name' => 'product_category',
              'type' => 'taxonomy',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5a04b93a18836',
                    'operator' => '==',
                    'value' => 'product-category',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'taxonomy' => 'product_cat',
              'field_type' => 'select',
              'allow_null' => 0,
              'add_term' => 1,
              'save_terms' => 0,
              'load_terms' => 0,
              'return_format' => 'object',
              'multiple' => 0,
            ),
            array (
              'key' => 'field_5a08fabc9ddbd',
              'label' => 'Choose Categories',
              'name' => 'choose_categories',
              'type' => 'taxonomy',
              'instructions' => 'Choose all the categories you want to display.',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5a04b93a18836',
                    'operator' => '==',
                    'value' => 'product-categories',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'taxonomy' => 'product_cat',
              'field_type' => 'multi_select',
              'allow_null' => 0,
              'add_term' => 1,
              'save_terms' => 0,
              'load_terms' => 0,
              'return_format' => 'id',
              'multiple' => 0,
            ),
            array (
              'key' => 'field_5a0662350bd27',
              'label' => 'Product Tag',
              'name' => 'product_tag',
              'type' => 'taxonomy',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5a04b93a18836',
                    'operator' => '==',
                    'value' => 'product-tag',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'taxonomy' => 'product_tag',
              'field_type' => 'select',
              'allow_null' => 0,
              'add_term' => 1,
              'save_terms' => 0,
              'load_terms' => 0,
              'return_format' => 'object',
              'multiple' => 0,
            ),
            array (
              'key' => 'field_5a052cf997860',
              'label' => 'Posts per page',
              'name' => 'posts_per_page',
              'type' => 'number',
              'instructions' => 'Write -1 to display all.',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5a04b93a18836',
                    'operator' => '==',
                    'value' => 'category',
                  ),
                ),
                array (
                  array (
                    'field' => 'field_5a04b93a18836',
                    'operator' => '==',
                    'value' => 'product-category',
                  ),
                ),
                array (
                  array (
                    'field' => 'field_5a04b93a18836',
                    'operator' => '==',
                    'value' => 'best-selling',
                  ),
                ),
                array (
                  array (
                    'field' => 'field_5a04b93a18836',
                    'operator' => '==',
                    'value' => 'popular-products',
                  ),
                ),
                array (
                  array (
                    'field' => 'field_5a04b93a18836',
                    'operator' => '==',
                    'value' => 'featured-products',
                  ),
                ),
                array (
                  array (
                    'field' => 'field_5a04b93a18836',
                    'operator' => '==',
                    'value' => 'recent-products',
                  ),
                ),
                array (
                  array (
                    'field' => 'field_5a04b93a18836',
                    'operator' => '==',
                    'value' => 'product-categories',
                  ),
                ),
                array (
                  array (
                    'field' => 'field_5a04b93a18836',
                    'operator' => '==',
                    'value' => 'product-tag',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => 4,
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'min' => -1,
              'max' => '',
              'step' => '',
            ),
            array (
              'key' => 'field_5a05382b8abf5',
              'label' => 'Columns per row',
              'name' => 'columns_per_row',
              'type' => 'select',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5a04b93a18836',
                    'operator' => '==',
                    'value' => 'category',
                  ),
                ),
                array (
                  array (
                    'field' => 'field_5a04b93a18836',
                    'operator' => '==',
                    'value' => 'product-category',
                  ),
                ),
                array (
                  array (
                    'field' => 'field_5a04b93a18836',
                    'operator' => '==',
                    'value' => 'best-selling',
                  ),
                ),
                array (
                  array (
                    'field' => 'field_5a04b93a18836',
                    'operator' => '==',
                    'value' => 'popular-products',
                  ),
                ),
                array (
                  array (
                    'field' => 'field_5a04b93a18836',
                    'operator' => '==',
                    'value' => 'featured-products',
                  ),
                ),
                array (
                  array (
                    'field' => 'field_5a04b93a18836',
                    'operator' => '==',
                    'value' => 'recent-products',
                  ),
                ),
                array (
                  array (
                    'field' => 'field_5a04b93a18836',
                    'operator' => '==',
                    'value' => 'product-categories',
                  ),
                ),
                array (
                  array (
                    'field' => 'field_5a04b93a18836',
                    'operator' => '==',
                    'value' => 'product-tag',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                1 => '1',
                2 => '2',
                3 => '3',
                4 => '4',
                5 => '5',
                6 => '6',
              ),
              'default_value' => array (
                0 => 4,
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
            ),
            array (
              'key' => 'field_5a04d237756b2',
              'label' => 'Custom Content',
              'name' => 'custom_content',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5a04b93a18836',
                    'operator' => '==',
                    'value' => 'custom-content',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
              'delay' => 0,
            ),
            array (
              'key' => 'field_5a04d36b5f38a',
              'label' => 'Styles',
              'name' => 'styles',
              'type' => 'true_false',
              'instructions' => 'Do you want to add styles?',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'message' => '',
              'default_value' => 0,
              'ui' => 1,
              'ui_on_text' => '',
              'ui_off_text' => '',
            ),
            array (
              'key' => 'field_5a04d7b65f38b',
              'label' => 'Background Color',
              'name' => 'background_color',
              'type' => 'color_picker',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5a04d36b5f38a',
                    'operator' => '==',
                    'value' => '1',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
            ),
            array (
              'key' => 'field_5a04d7db5f38c',
              'label' => 'Background Image',
              'name' => 'background_image',
              'type' => 'image',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5a04d36b5f38a',
                    'operator' => '==',
                    'value' => '1',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'url',
              'preview_size' => 'thumbnail',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => '',
              'mime_types' => '',
            ),
            array (
              'key' => 'field_5a04d8585f38e',
              'label' => 'Background Size',
              'name' => 'background_size',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5a04d36b5f38a',
                    'operator' => '==',
                    'value' => '1',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => 'cover',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_5a04d8355f38d',
              'label' => 'Background Position',
              'name' => 'background_position',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5a04d36b5f38a',
                    'operator' => '==',
                    'value' => '1',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => 'center center',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_5a04d8795f38f',
              'label' => 'Background Repeat',
              'name' => 'background_repeat',
              'type' => 'select',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5a04d36b5f38a',
                    'operator' => '==',
                    'value' => '1',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'repeat' => 'repeat',
                'repeat-x' => 'repeat-x',
                'repeat-y' => 'repeat-y',
                'no-repeat' => 'no-repeat',
                'initial' => 'initial',
                'inherit' => 'inherit',
              ),
              'default_value' => array (
                0 => 'no-repeat',
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 0,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
            ),
            array (
              'key' => 'field_5a04d9325f390',
              'label' => 'Parallax',
              'name' => 'parallax',
              'type' => 'true_false',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5a04d36b5f38a',
                    'operator' => '==',
                    'value' => '1',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'message' => 'Add parallax effect?',
              'default_value' => 0,
              'ui' => 0,
              'ui_on_text' => '',
              'ui_off_text' => '',
            ),
            array (
              'key' => 'field_5a04da1865ede',
              'label' => 'Headings Color',
              'name' => 'headings_color',
              'type' => 'color_picker',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5a04d36b5f38a',
                    'operator' => '==',
                    'value' => '1',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
            ),
            array (
              'key' => 'field_5a04da4465edf',
              'label' => 'Text Color',
              'name' => 'text_color',
              'type' => 'color_picker',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5a04d36b5f38a',
                    'operator' => '==',
                    'value' => '1',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
            ),
            array (
              'key' => 'field_5a04da5a65ee0',
              'label' => 'Link Color',
              'name' => 'link_color',
              'type' => 'color_picker',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5a04d36b5f38a',
                    'operator' => '==',
                    'value' => '1',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
            ),
            array (
              'key' => 'field_5a04da8765ee1',
              'label' => 'Link Hover',
              'name' => 'link_hover',
              'type' => 'color_picker',
              'instructions' => 'Color to display when you mouse over a link.',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5a04d36b5f38a',
                    'operator' => '==',
                    'value' => '1',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
            ),
            array (
              'key' => 'field_5a04df8d9eba0',
              'label' => 'Padding',
              'name' => 'padding',
              'type' => 'group',
              'instructions' => 'Remember to add units like 10vh or 50px',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5a04d36b5f38a',
                    'operator' => '==',
                    'value' => '1',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'layout' => 'row',
              'sub_fields' => array (
                array (
                  'key' => 'field_5a04e1c0bb043',
                  'label' => 'Large Devices',
                  'name' => 'lg_devices',
                  'type' => 'group',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'layout' => 'table',
                  'sub_fields' => array (
                    array (
                      'key' => 'field_5a04e23691ddc',
                      'label' => 'Padding Top',
                      'name' => 'padding_top',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                    ),
                    array (
                      'key' => 'field_5a04e23e91ddd',
                      'label' => 'Padding Bottom',
                      'name' => 'padding_bottom',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                    ),
                  ),
                ),
                array (
                  'key' => 'field_5a04e299c49cf',
                  'label' => 'Medium Devices',
                  'name' => 'md_devices',
                  'type' => 'group',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'layout' => 'table',
                  'sub_fields' => array (
                    array (
                      'key' => 'field_5a04e2a8c49d0',
                      'label' => 'Padding Top',
                      'name' => 'padding_top',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                    ),
                    array (
                      'key' => 'field_5a04e2b3c49d1',
                      'label' => 'Padding Bottom',
                      'name' => 'padding_bottom',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                    ),
                  ),
                ),
                array (
                  'key' => 'field_5a04e2c4c49d2',
                  'label' => 'Small Devices',
                  'name' => 'sm_devices',
                  'type' => 'group',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'layout' => 'table',
                  'sub_fields' => array (
                    array (
                      'key' => 'field_5a04e2c4c49d3',
                      'label' => 'Padding Top',
                      'name' => 'padding_top',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                    ),
                    array (
                      'key' => 'field_5a04e2c4c49d4',
                      'label' => 'Padding Bottom',
                      'name' => 'padding_bottom',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                    ),
                  ),
                ),
                array (
                  'key' => 'field_5a04e2d3c49d5',
                  'label' => 'Extra Small Devices',
                  'name' => 'xs_devices',
                  'type' => 'group',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'layout' => 'table',
                  'sub_fields' => array (
                    array (
                      'key' => 'field_5a04e2d3c49d6',
                      'label' => 'Padding Top',
                      'name' => 'padding_top',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                    ),
                    array (
                      'key' => 'field_5a04e2d3c49d7',
                      'label' => 'Padding Bottom',
                      'name' => 'padding_bottom',
                      'type' => 'text',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                      'prepend' => '',
                      'append' => '',
                      'maxlength' => '',
                    ),
                  ),
                ),
              ),
            ),
            array (
              'key' => 'field_5a04dae365ee2',
              'label' => 'Grid',
              'name' => 'grid',
              'type' => 'true_false',
              'instructions' => 'Do you want to change the container grid?',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'message' => '',
              'default_value' => 0,
              'ui' => 1,
              'ui_on_text' => '',
              'ui_off_text' => '',
            ),
            array (
              'key' => 'field_5a04dc9665ee3',
              'label' => 'Bootstrap grid',
              'name' => 'bootstrap_grid',
              'type' => 'text',
              'instructions' => 'Boostrap 3.3.7',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5a04dae365ee2',
                    'operator' => '==',
                    'value' => '1',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => 'col-xs-12 col-sm- 10 col-sm-offset-1',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
            ),
            array (
              'key' => 'field_5a04dd0a65ee4',
              'label' => 'Full width',
              'name' => 'full_width',
              'type' => 'true_false',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5a04dae365ee2',
                    'operator' => '==',
                    'value' => '1',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'message' => 'Make this section full width?',
              'default_value' => 0,
              'ui' => 0,
              'ui_on_text' => '',
              'ui_off_text' => '',
            ),
            array (
              'key' => 'field_5a04dd6265ee5',
              'label' => 'Animation',
              'name' => 'animation',
              'type' => 'true_false',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'message' => '',
              'default_value' => 0,
              'ui' => 1,
              'ui_on_text' => '',
              'ui_off_text' => '',
            ),
            array (
              'key' => 'field_5a04ddaf65ee7',
              'label' => 'Section Animation',
              'name' => 'section_animation',
              'type' => 'select',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => array (
                array (
                  array (
                    'field' => 'field_5a04dd6265ee5',
                    'operator' => '==',
                    'value' => '1',
                  ),
                ),
              ),
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'bounce' => 'bounce',
                'flash' => 'flash',
                'pulse' => 'pulse',
                'rubberBand' => 'rubberBand',
                'shake' => 'shake',
                'swing' => 'swing',
                'tada' => 'tada',
                'wobble' => 'wobble',
                'jello' => 'jello',
                'bounceIn' => 'bounceIn',
                'bounceInDown' => 'bounceInDown',
                'bounceInLeft' => 'bounceInLeft',
                'bounceInRight' => 'bounceInRight',
                'bounceInUp' => 'bounceInUp',
                'bounceOut' => 'bounceOut',
                'bounceOutDown' => 'bounceOutDown',
                'bounceOutLeft' => 'bounceOutLeft',
                'bounceOutRight' => 'bounceOutRight',
                'bounceOutUp' => 'bounceOutUp',
                'fadeIn' => 'fadeIn',
                'fadeInDown' => 'fadeInDown',
                'fadeInDownBig' => 'fadeInDownBig',
                'fadeInLeft' => 'fadeInLeft',
                'fadeInLeftBig' => 'fadeInLeftBig',
                'fadeInRight' => 'fadeInRight',
                'fadeInRightBig' => 'fadeInRightBig',
                'fadeInUp' => 'fadeInUp',
                'fadeInUpBig' => 'fadeInUpBig',
                'fadeOut' => 'fadeOut',
                'fadeOutDown' => 'fadeOutDown',
                'fadeOutDownBig' => 'fadeOutDownBig',
                'fadeOutLeft' => 'fadeOutLeft',
                'fadeOutLeftBig' => 'fadeOutLeftBig',
                'fadeOutRight' => 'fadeOutRight',
                'fadeOutRightBig' => 'fadeOutRightBig',
                'fadeOutUp' => 'fadeOutUp',
                'fadeOutUpBig' => 'fadeOutUpBig',
                'flip' => 'flip',
                'flipInX' => 'flipInX',
                'flipInY' => 'flipInY',
                'flipOutX' => 'flipOutX',
                'flipOutY' => 'flipOutY',
                'lightSpeedIn' => 'lightSpeedIn',
                'lightSpeedOut' => 'lightSpeedOut',
                'rotateIn' => 'rotateIn',
                'rotateInDownLeft' => 'rotateInDownLeft',
                'rotateInDownRight' => 'rotateInDownRight',
                'rotateInUpLeft' => 'rotateInUpLeft',
                'rotateInUpRight' => 'rotateInUpRight',
                'rotateOut' => 'rotateOut',
                'rotateOutDownLeft' => 'rotateOutDownLeft',
                'rotateOutDownRight' => 'rotateOutDownRight',
                'rotateOutUpLeft' => 'rotateOutUpLeft',
                'rotateOutUpRight' => 'rotateOutUpRight',
                'slideInUp' => 'slideInUp',
                'slideInDown' => 'slideInDown',
                'slideInLeft' => 'slideInLeft',
                'slideInRight' => 'slideInRight',
                'slideOutUp' => 'slideOutUp',
                'slideOutDown' => 'slideOutDown',
                'slideOutLeft' => 'slideOutLeft',
                'slideOutRight' => 'slideOutRight',
                'zoomIn' => 'zoomIn',
                'zoomInDown' => 'zoomInDown',
                'zoomInLeft' => 'zoomInLeft',
                'zoomInRight' => 'zoomInRight',
                'zoomInUp' => 'zoomInUp',
                'zoomOut' => 'zoomOut',
                'zoomOutDown' => 'zoomOutDown',
                'zoomOutLeft' => 'zoomOutLeft',
                'zoomOutRight' => 'zoomOutRight',
                'zoomOutUp' => 'zoomOutUp',
                'hinge' => 'hinge',
                'rollIn' => 'rollIn',
                'rollOut' => 'rollOut',
              ),
              'default_value' => array (
              ),
              'allow_null' => 0,
              'multiple' => 0,
              'ui' => 1,
              'ajax' => 0,
              'return_format' => 'value',
              'placeholder' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
      ),
      'button_label' => 'Add Row',
      'min' => '',
      'max' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'theme-settings',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

endif;