<?php
/**
* Set Up Page
* General Settings
*
* @author       xWaZzo @FrontendNinja
* @version      1.0.0
* @package      Advanced Custom Fields
* @subpackage   Front End Ninja
*/
if( function_exists('acf_add_local_field_group') ):

  acf_add_local_field_group(array (
    'key' => 'group_59b843125de92',
    'title' => 'Control Panel',
    'fields' => array (
      array (
        'key' => 'field_59b8440cbf64e',
        'label' => 'Header',
        'name' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'left',
        'endpoint' => 0,
      ),
      array (
        'key' => 'field_59b8484a68ed1',
        'label' => 'HTML Before <body>',
        'name' => 'header_html_before_body',
        'type' => 'acf_code_field',
        'instructions' => 'Add html and javascript before the </head> tag.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '<!-- <script type="text/javascript"></script> -->',
        'placeholder' => '',
        'mode' => 'htmlmixed',
        'theme' => 'monokai',
      ),
      array (
        'key' => 'field_59b848ef68ed3',
        'label' => 'HTML After <body>',
        'name' => 'header_html_after_body',
        'type' => 'acf_code_field',
        'instructions' => 'Add html and javascript after the <body> tag.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '<!-- <script type="text/javascript"></script> -->',
        'placeholder' => '',
        'mode' => 'htmlmixed',
        'theme' => 'monokai',
      ),
      array (
        'key' => 'field_59b852bdbc1f3',
        'label' => 'Footer',
        'name' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'left',
        'endpoint' => 0,
      ),
      array (
        'key' => 'field_59b85382bc1f5',
        'label' => 'HTML Before </body>',
        'name' => 'footer_html_before_body',
        'type' => 'acf_code_field',
        'instructions' => 'Add html and javascript before the </body> closing tag.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '<!-- <script type="text/javascript"></script> -->',
        'placeholder' => '',
        'mode' => 'htmlmixed',
        'theme' => 'monokai',
      ),
      array (
        'key' => 'field_59b858aebc1f7',
        'label' => 'Appearance',
        'name' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'left',
        'endpoint' => 0,
      ),
      array (
        'key' => 'field_59b85a1dbc1f9',
        'label' => 'Logotype',
        'name' => 'logotype',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'preview_size' => 'medium',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array (
        'key' => 'field_59b85e01f081e',
        'label' => 'Favicon',
        'name' => 'favicon',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'preview_size' => 'full',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array (
        'key' => 'field_59b85e1ff081f',
        'label' => 'Default Image',
        'name' => 'default_image',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'preview_size' => 'medium',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array (
        'key' => 'field_59b85e2ef0820',
        'label' => 'Error 404',
        'name' => 'error_404',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'preview_size' => 'medium',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array (
        'key' => 'field_59b85e6bf0821',
        'label' => 'Css Style',
        'name' => 'css_style',
        'type' => 'acf_code_field',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'mode' => 'css',
        'theme' => 'monokai',
      ),
      array (
        'key' => 'field_59b85e90f0822',
        'label' => 'Alert',
        'name' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'left',
        'endpoint' => 0,
      ),
      array (
        'key' => 'field_59b862cf793e7',
        'label' => 'Alert Type',
        'name' => 'alert_type',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => 'Modal Alert?',
        'default_value' => 0,
        'ui' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
      array (
        'key' => 'field_59b85ea5f0823',
        'label' => 'Alert Title',
        'name' => 'alert_title',
        'type' => 'text',
        'instructions' => 'Leave empty if you don\'t need a title',
        'required' => 0,
        'conditional_logic' => array (
          array (
            array (
              'field' => 'field_59b862cf793e7',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_59b85f4ef0824',
        'label' => 'Alert Description',
        'name' => 'alert_description',
        'type' => 'wysiwyg',
        'instructions' => 'Your main description for the alert.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 1,
        'delay' => 0,
      ),
      array (
        'key' => 'field_59b85f87f0825',
        'label' => 'Alert Url',
        'name' => 'alert_url',
        'type' => 'url',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array (
          array (
            array (
              'field' => 'field_59b862cf793e7',
              'operator' => '!=',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array (
        'key' => 'field_59b86247793e5',
        'label' => 'Alert Style',
        'name' => 'alert_style',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array (
          array (
            array (
              'field' => 'field_59b862cf793e7',
              'operator' => '!=',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array (
          'alert-primary' => 'Primary',
          'alert-success' => 'Success',
          'alert-info' => 'Info',
          'alert-warning' => 'Warning',
          'alert-danger' => 'Danger',
        ),
        'default_value' => array (
        ),
        'allow_null' => 1,
        'multiple' => 0,
        'ui' => 0,
        'ajax' => 0,
        'return_format' => 'value',
        'placeholder' => '',
      ),
      array (
        'key' => 'field_59b869930bc7c',
        'label' => 'Social Networks',
        'name' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'left',
        'endpoint' => 0,
      ),
      array (
        'key' => 'field_59b869a70bc7d',
        'label' => 'Social Network',
        'name' => 'social_network',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 0,
        'layout' => 'table',
        'button_label' => '',
        'sub_fields' => array (
          array (
            'key' => 'field_59b869c00bc7e',
            'label' => 'Title',
            'name' => 'title',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'Facebook',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array (
            'key' => 'field_59b869d10bc7f',
            'label' => 'Icon',
            'name' => 'icon',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'choices' => array (
              '500px' => '500px',
              'amazon' => 'amazon',
              'android' => 'android',
              'behance' => 'behance',
              'behance-square' => 'behance-square',
              'deviantart' => 'deviantart',
              'dropbox' => 'dropbox',
              'envelope' => 'envelope',
              'facebook' => 'facebook',
              'facebook-official' => 'facebook-official',
              'facebook-square' => 'facebook-square',
              'flickr' => 'flickr',
              'foursquare' => 'foursquare',
              'google-plus' => 'google-plus',
              'instagram' => 'instagram',
              'linkedin' => 'linkedin',
              'linkedin-square' => 'linkedin-square',
              'pinterest' => 'pinterest',
              'pinterest-p' => 'pinterest-p',
              'pinterest-square' => 'pinterest-square',
              'skype' => 'skype',
              'spotify' => 'spotify',
              'tumblr' => 'tumblr',
              'tumblr-square' => 'tumblr-square',
              'twitter' => 'twitter',
              'twitter-square' => 'twitter-square',
              'vimeo' => 'vimeo',
              'vimeo-square' => 'vimeo-square',
              'vine' => 'vine',
              'whatsapp' => 'whatsapp',
              'yelp' => 'yelp',
              'youtube' => 'youtube',
              'youtube-play' => 'youtube-play',
              'youtube-square' => 'youtube-square',
            ),
            'default_value' => array (
              0 => 'facebook',
            ),
            'allow_null' => 1,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
          ),
          array (
            'key' => 'field_59b86b2467572',
            'label' => 'Custom Icon',
            'name' => 'custom_icon',
            'type' => 'text',
            'instructions' => '<a href="http://fontawesome.io/icons/" target="_blank">Available Icons</a>',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'circle-o',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array (
            'key' => 'field_59b86a5c0bc80',
            'label' => 'URL',
            'name' => 'url',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
          ),
        ),
      ),
      array (
        'key' => 'field_59b8657e2809d',
        'label' => 'Credits',
        'name' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'left',
        'endpoint' => 0,
      ),
      array (
        'key' => 'field_59b866683c839',
        'label' => 'Project Manager',
        'name' => '',
        'type' => 'message',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '<a href="http://frontend.ninja/author/xwazzo/">Carlos González</a>',
        'new_lines' => 'wpautop',
        'esc_html' => 0,
      ),
      array (
        'key' => 'field_59b865bd2809f',
        'label' => 'Front End Designer',
        'name' => '',
        'type' => 'message',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '<a href="http://frontend.ninja/author/lima/">Libertad Madrigal</a>',
        'new_lines' => 'wpautop',
        'esc_html' => 0,
      ),
      array (
        'key' => 'field_59b866b47f88c',
        'label' => 'Back End Developer',
        'name' => '',
        'type' => 'message',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '<a href="http://frontend.ninja/author/xwazzo/">Carlos González</a>',
        'new_lines' => 'wpautop',
        'esc_html' => 0,
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-set-up',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

endif;